DROP DATABASE IF EXISTS PERSONAL;
CREATE DATABASE PERSONAL;
USE PERSONAL;
 
CREATE TABLE DEPARTAMENTO (
	IDDEPARTAMENTO INT PRIMARY KEY,
	DEPARTAMENTO VARCHAR(50) NOT NULL
); 

CREATE TABLE EMPLEADO (
	IDEMPLEADO INT PRIMARY KEY,
	NOMBRE VARCHAR(100),
	IDDEPARTAMENTO INT,
	FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);

ALTER TABLE EMPLEADO ADD COLUMN HIJO TINYINT;  -- PARA AÑADIR UNA COLUMNA A UNA TABLA USAMOS ALTER TABLE --

INSERT INTO DEPARTAMENTO VALUES (1, 'Ventas');
INSERT INTO DEPARTAMENTO VALUES (2, 'Compas');
INSERT INTO DEPARTAMENTO VALUES (3, 'Recursos Humanos');

INSERT INTO EMPLEADO VALUES (12, 'Lucas Perez', 1, 2);
INSERT INTO EMPLEADO VALUES (13, 'Marcos Ramírez', 1, 3);
INSERT INTO EMPLEADO VALUES (14, 'Lucía Berrocal', 2, 4);
INSERT INTO EMPLEADO VALUES (15, 'Laura Cascos', 2, 4);
INSERT INTO EMPLEADO VALUES (16, 'Paquito García', 3, 2);
INSERT INTO EMPLEADO VALUES (17, 'Quique Fernández', 3, 1);

ALTER TABLE EMPLEADO ADD COLUMN FECHA_INGRESO DATE;

UPDATE `personal`.`empleado` SET `FECHA_INGRESO` = '2021-10-01' WHERE (`IDEMPLEADO` = '12');
UPDATE `personal`.`empleado` SET `FECHA_INGRESO` = '2022-10-02' WHERE (`IDEMPLEADO` = '13');
UPDATE `personal`.`empleado` SET `FECHA_INGRESO` = '2017-04-04' WHERE (`IDEMPLEADO` = '14');
UPDATE `personal`.`empleado` SET `FECHA_INGRESO` = '2004-04-03' WHERE (`IDEMPLEADO` = '15');
UPDATE `personal`.`empleado` SET `FECHA_INGRESO` = '2003-12-12' WHERE (`IDEMPLEADO` = '16');
UPDATE `personal`.`empleado` SET `FECHA_INGRESO` = '2010-05-05' WHERE (`IDEMPLEADO` = '17');

SELECT NOMBRE, IDDEPARTAMENTO FROM EMPLEADO
WHERE IDDEPARTAMENTO=3
ORDER BY NOMBRE;

SELECT NOMBRE, IDDEPARTAMENTO FROM EMPLEADO
WHERE NOT IDDEPARTAMENTO=3
ORDER BY NOMBRE;



SELECT * FROM EMPLEADO
WHERE HIJO <=1
ORDER BY HIJO;



ALTER TABLE DEPARTAMENTO
MODIFY COLUMN DEPARTAMENTO VARCHAR(100) NOT NULL;

ALTER TABLE EMPLEADO
MODIFY COLUMN NOMBRE VARCHAR(50) NOT NULL;


